name: ovidhan
description: "A Dictionarry app for Bengali language"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  isar_community: ^3.3.0-dev.2
  isar_community_flutter_libs: ^3.3.0-dev.2
  path_provider: ^2.1.5
  path: ^1.9.1
  csv: ^7.1.0
  collection: ^1.19.0
  flutter_slidable: ^4.0.3
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  isar_community_generator: ^3.3.0-dev.2

flutter:
  assets:
    - assets/default.isar
  uses-material-design: true
  fonts:
    - family: Noto Sans Bengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansBengali-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSansBengali-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansBengali-Black.ttf
          weight: 900
        - asset: assets/fonts/NotoSansBengali_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansBengali_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansBengali_Condensed-Thin.ttf
          weight: 100
